# Сборка клиента
client:
    fasm client.asm client
    chmod +x client

# Сборка сервера (когда он будет)
server:
    fasm server.asm server
    chmod +x server

# Сборка всего
all: client server